### ISSUE TITLE
Format of training dataset

### ISSUE THREAD

**Issue by tteguayco** [arnabd64/Fine-Tune-Instruct-Pix2Pix#1]
Hey @arnabd64,

Thanks for sharing a very helpful sample notebook for fine tuning IP2P. Could you share a sample of the training set as well? Just to get an idea of how the format looks like.

Thank you!

**Comment by arnabd64** [comment]
Sorry @tteguayco this project was part of my company's internal project so I am forbidden to share the dataset with anyone. But I can share an open source dataset that should work with my training notebook. https://huggingface.co/datasets/timbrooks/instructpix2pix-clip-filtered

**Comment by tteguayco** [comment]
Thank you, @arnabd64 !

**Comment by tteguayco** [comment]
Sorry for re-opening, @arnabd64, but this link here (https://huggingface.co/docs/diffusers/en/training/create_dataset) doesn't really explain how to create a Hugging Face dataset consisting of both images and captions/text. It does for unconditional image generation only.

What's the format you used for adding the text captions to your dataset?

**Comment by arnabd64** [comment]
@tteguayco I have uploaded a new `dataset-creator.ipynb` that should help you to process your dataset. 

I would advice you to follow these steps to properly run the notebook.

1. Git clone the repository on your local machine.
2. Create 2 directories, `original` and `edited`.
3. Copy the first original image to `original` renamed as `image_1.jpg` or `image_1.png` and the corresponding edited image should be under the `edited` directory renamed as `image_1.jpg` or `image_1.png`.
4. The prompt for `image_1` should be placed on the first line of `prompts.txt` file, the prompt for `image_2` should be placed on the second line and so on.
5. Run the Notebook to prepare your dataset

**Comment by tteguayco** [comment]
You rock, @arnabd64! So after inspecting your new script, I assume `before`, `after` and `prompt` are the fields that your training script `stable-diffusion-finetuner.ipynb` expects? That's the only piece I'm still not able to link.

**Comment by arnabd64** [comment]
@tteguayco, In my training notebook you can tweak the parameters: `--original_image_column`, `--edit_prompt` and `--edited_image` to match the key names that you wish to use. I have used `before`, `after` and `prompt` as I find these key names to be convienient.

I hope now you can start with the fine tuning process. If everything is okay then do close this issue and if there is some other issue then feel free to raise a new issue. Happy Fine Tuning.

**Comment by tteguayco** [comment]
Thanks again, you nailed it!
